const WishListActions = {
  ADD_ITEM_TO_WISHLIST: "ADD_ITEM_TO_WISHLIST",
  REMOVE_ITEM_FROM_WISHLIST: "REMOVE_ITEM_FROM_WISHLIST",
  DECREASE_QUANTITY_IN_WISHLIST_ITEM: "DECREASE_QUANTITY_IN_WISHLIST_ITEM",
};

export default WishListActions;